name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Check build & Test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: List available ports
        run: sudo netstat -lpn

      - name: Build
        run: zig build -Dgithub-client-id=test_gh_client_id -Dgithub-client-secret=test_gh_client_secret

      - name: Test
        run: zig test -I lib/c/sqlite -lsqlite3 src/test.zig
