name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine
      # ports:
      #   - 3010:3010
    steps:
      - uses: actions/checkout@v4
      - name: Install zig
        run: apk add zig
      - name: Build
        run: zig build
      - name: Test
        run: zig test src/tests.zig
