name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Check build & Test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GITHUB_CLIENT_ID: test_gh_client_id
      GITHUB_SECRET: test_github_secret
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build
        run: zig build

      - name: Test
        run: zig build test --summary all
