name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Check build & Test
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install zig
        run: apk add "zig=~0.14"
      - name: Build
        run: zig build -Dgithub-client-id=test_gh_client_id -Dgithub-client-secret=test_gh_client_secret
      - name: Test
        run: zig test -I lib/c/sqlite -lsqlite3 src/test.zig
